In [3]:
import os
from tkinter import Image
import pandas as pd
from torchvision.io import read_image
from torch.utils.data import Dataset
import torch
import PIL
from PIL import Image
from torchvision.transforms.functional import to_pil_image
import numpy as np
from torch.utils.data import DataLoader
from torchvision.io import read_image
from torchvision import transforms


In [4]:
read_image("C:\\Users\\user\\Desktop\\temp\\back\\0036_c2_f0062476.jpg").shape

RuntimeError: [Errno 2] No such file or directory: 'C:\Users\user\Desktop\temp\back\0036_c2_f0062476.jpg'

In [ ]:

_target = np.array(['front', 'back', 'left', 'right'])

class TrainRawData(Dataset):
    def __init__(self, dir, img_size = (150, 80)):
        self.target = _target
        self.dir = dir
        self.img_size = img_size
        imgs = []
        labels = []
        for t in self.target:
            image_files = os.listdir(os.path.join(dir, t))
            for file in image_files:
                imgs += [os.path.join(dir, t, file)]
                labels += [t]

        self.images = imgs
        self.labels = labels
        self.resize = transforms.Resize(self.img_size)
    def __len__(self):
        return len(self.labels)

    def __getitem__(self, index):
        img = read_image(self.images[index])        
        img = self.resize(img)
        label = self.labels[index]

        return img, label

dir = "C:\\Users\\user\\Desktop\\pose-angle"
dataset = TrainRawData(dir)
predictor = openpifpaf.Predictor(checkpoint='shufflenetv2k16')
skeletons = []
labels = []
dataloader = DataLoader(dataset, batch_size = 32, shuffle= False)

for batch, (X, y) in enumerate(dataloader):
    images =[]
    for img in X:
        images += [to_pil_image(img)]

    
    predicts = predictor.pil_images(images)
    

    for p, y in zip(predicts, y):
        if not p:
            continue
        if not p[0]:
            continue
        
        skel = p[0][0].data
        skel[:, 1:2] = skel[:, 1:2]/150
        skel[:, 0:1] = skel[:, 0:1]/50
        new_skel = (skel[5] + skel[6])/2
        skeleton = np.append(skel, new_skel[np.newaxis, :], axis = 0)
        skeletons += [skeleton]
        labels += [y]
        

NameError: name 'openpifpaf' is not defined

In [ ]:
len(skeletons)

NameError: name 'skeletons' is not defined

In [ ]:
from PIL import Image
img = Image.open("C:\\Users\\user\\Desktop\\temp\\back\\0036_c2_f0062476.jpg")


FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\user\\Desktop\\temp\\back\\0036_c2_f0062476.jpg'

In [ ]:
img.size

NameError: name 'img' is not defined

In [ ]:
predictor = openpifpaf.Predictor(checkpoint='shufflenetv2k16')
skeletons = []
labels = []

target = np.array(['front', 'back', 'left', 'right'])


for k, (i, l) in enumerate(dataset):
    image = to_pil_image(i)
    predictions, _, _ = predictor.pil_image(image)
    label = target == l
    if not predictions:
        continue

    skt = np.append(predictions[0].data, (predictions[0].data[5] + predictions[0].data[6])/2).reshape(-1, 3)
    skt[:, 1:2] = skt[:, 1:2]/150
    skt[:, 0:1] = skt[:, 0:1]/80


    if len(skeletons) ==0:
        skeletons = skt[np.newaxis, :]
        labels = label[np.newaxis, :]
    else :
        skeletons = np.append(skeletons, skt[np.newaxis, :], axis = 0)
        labels = np.append(labels, label[np.newaxis, :], axis = 0)

# print('save file')
# np.save("./skeletons",skeletons)
# print('skeletons.npy done')
# np.save('./labels', labels)
# print('labels.npy done')

NameError: name 'openpifpaf' is not defined

In [ ]:
skeletons

array([[[ 0.43082315,  0.12399478,  0.7198429 ],
        [ 0.46405753,  0.10532612,  0.74980545],
        [ 0.38267812,  0.10790325,  0.75062114],
        ...,
        [ 0.5836378 ,  0.8786189 ,  0.8731816 ],
        [ 0.38348863,  0.87021655,  0.8877806 ],
        [ 0.45100838,  0.21286431,  0.9859555 ]],

       [[-0.14      , -0.03333334,  0.        ],
        [-0.14      , -0.03333334,  0.        ],
        [-0.14      , -0.03333334,  0.        ],
        ...,
        [ 0.578619  ,  0.8178058 ,  0.8126712 ],
        [ 0.3860769 ,  0.83724546,  0.819913  ],
        [ 0.5202601 ,  0.16737348,  0.8793916 ]],

       [[ 0.43231776,  0.12139782,  0.9094761 ],
        [ 0.49593487,  0.10381035,  0.8891215 ],
        [ 0.39445677,  0.10155147,  0.8944227 ],
        ...,
        [ 0.5812443 ,  0.875796  ,  0.942882  ],
        [ 0.48856452,  0.8841891 ,  0.9106627 ],
        [ 0.46228835,  0.21491969,  0.96181136]],

       ...,

       [[ 0.3813506 ,  0.15464474,  0.7758648 ],
        [ 0

In [1]:
from datasets import AlphaposeSkeletonData

train_json_dir = "C:\\Users\\user\\Desktop\\alphapose_json"
train_image_dir = "C:\\Users\\user\\Desktop\\RE-ID\\datasets\\DukeMTMC-reID\\query"
valid_json_dir = "C:\\Users\\user\\Desktop\\alphapose_json_valid"
valid_image_idr =  "C:\\Users\\user\\Desktop\\RE-ID\\datasets\\DukeMTMC-reID\\query"

train_dataset = AlphaposeSkeletonData(train_json_dir, train_image_dir)
valid_dataset = AlphaposeSkeletonData(valid_json_dir, valid_image_idr)
train_dataset.__len__(), valid_dataset.__len__()

(652, 124)

In [2]:
train_dataset.skeletons.shape

torch.Size([652, 18, 3])

In [7]:
from train import train, _A
from model import GCN
import torch

model = GCN(3, 4, torch.tensor(_A).float())

train(model, train_dataset, valid_dataset, epochs= 200, batch_size=16, learning_rate = 1e-3)

learning_rate : 0.0001
batch_size : 16
epochs : 200
Epoch 1
---------------------------------
loss: 407.582764 [    0/  652]
loss: 144.932434 [  100/  652]
loss: 56.787720 [  200/  652]
loss: 43.124741 [  300/  652]
loss: 27.741343 [  400/  652]
loss: 27.102057 [  500/  652]
loss: 10.370781 [  600/  652]
val_loss: 132.578888
---------------------------------
Epoch 2
---------------------------------
loss: 18.462425 [    0/  652]
loss: 8.960799 [  100/  652]
loss: 15.589380 [  200/  652]
loss: 12.277332 [  300/  652]
loss: 13.656728 [  400/  652]
loss: 16.868389 [  500/  652]
loss: 8.770592 [  600/  652]
val_loss: 97.125137
---------------------------------
Epoch 3
---------------------------------
loss: 9.109599 [    0/  652]
loss: 14.732875 [  100/  652]
loss: 19.822668 [  200/  652]
loss: 15.070358 [  300/  652]
loss: 10.290693 [  400/  652]
loss: 14.908043 [  500/  652]
loss: 4.637093 [  600/  652]
val_loss: 127.482117
---------------------------------
Epoch 4
----------------------

In [5]:
import numpy as np
_target = np.array(['front', 'back', 'left', 'right'])

model.eval()
s = 0
with torch.no_grad():
    for X, y in valid_dataset:
        pred = model(X.unsqueeze(0))
        s += int(_target[pred.argmax()]== _target[y.argmax()])

print("accruacy : ", s/valid_dataset.__len__())


accruacy :  0.4112903225806452


In [ ]:
from classificatoin import image_classiciation

image_classiciation(model,)

In [12]:
from model import *
import torch
import numpy as npd
_target = np.array(['front', 'back', 'left', 'right'])
_A =\
    [
        [1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1],
        [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1], #11
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1], #12
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0], #13
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0], #14
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0], #15
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0], #16
        [1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1]  #17
    ]
    

model = GCN(3, 4, torch.tensor(_A).float())
model.load_state_dict(torch.load("./model_save/model_05_12_13_43_weight.pth"))
model.eval
s = 0
with torch.no_grad():
    for X, y in valid_dataset:
        pred = model(X.unsqueeze(0))
        s += int(_target[pred.argmax()]== _target[y.argmax()])

print("accruacy : ", s/valid_dataset.__len__())

RuntimeError: Error(s) in loading state_dict for GCN:
	Missing key(s) in state_dict: "feature_extractor.4.fc.weight", "feature_extractor.4.fc.bias", "feature_extractor.6.fc.weight", "feature_extractor.6.fc.bias", "feature_extractor.8.fc.weight", "feature_extractor.8.fc.bias", "feature_extractor.10.fc.weight", "feature_extractor.10.fc.bias", "feature_extractor.12.fc.weight", "feature_extractor.12.fc.bias", "feature_extractor.15.weight", "feature_extractor.15.bias". 
	Unexpected key(s) in state_dict: "feature_extractor.4.weight", "feature_extractor.4.bias". 
	size mismatch for feature_extractor.0.fc.weight: copying a param with shape torch.Size([18, 3]) from checkpoint, the shape in current model is torch.Size([4, 3]).
	size mismatch for feature_extractor.0.fc.bias: copying a param with shape torch.Size([18]) from checkpoint, the shape in current model is torch.Size([4]).
	size mismatch for feature_extractor.2.fc.weight: copying a param with shape torch.Size([4, 18]) from checkpoint, the shape in current model is torch.Size([8, 4]).
	size mismatch for feature_extractor.2.fc.bias: copying a param with shape torch.Size([4]) from checkpoint, the shape in current model is torch.Size([8]).

In [40]:
import os
from tkinter import Image
import pandas as pd
from torchvision.io import read_image
from torch.utils.data import Dataset
import torch
import PIL
from PIL import Image
import openpifpaf
from torchvision.transforms.functional import to_pil_image
import numpy as np
from torch.utils.data import DataLoader
from torchvision import transforms
import json
from sklearn.utils import resample
_target = np.array(['front', 'back', 'left', 'right'])

class AlphaposeSkeletonData(Dataset):
    def __init__(self, json_dir, image_dir):
        skeletons = []
        labels = []
        for pose_name in os.listdir(json_dir):
            json_file = os.path.join(json_dir, pose_name)
            with open(json_file, 'r') as f:
                json_data = json.load(f)
            dic = {}
            for data in json_data:
                cls = data['cls']
                if cls != 0:
                    continue
                image_id = data['image_id']
                box = data['box']
                keypoints = np.array(data['keypoints']).reshape(-1, 3)
                x1, y1, x2, y2 = box
                temp = (x2 - x1) * (y2 - y1)
                if  temp < 0:
                    temp *= -1
                
                keypoints = np.append(keypoints,(keypoints[5:6] + keypoints[6:7])/2, axis = 0)
                if image_id in dic.keys():
                    if temp > dic[image_id]['box']:
                        dic[image_id]['box'] = temp
                        dic[image_id]['keypoints'] = keypoints
                                     
                else :                     
                    dic[image_id] = {"keypoints" : keypoints, "box" : temp, 'label' : (_target == pose_name[:-5]).astype('int')}
            
            for id, values in dic.items():
                skeletons += [values['keypoints']]
                labels += [values['label']]
        skeletons = np.array(skeletons)
        labels = np.array(labels)
        
        min_len = min((labels[:,0]==1).sum(),
        (labels[:,1]==1).sum(),
        (labels[:,2]==1).sum(),
        (labels[:,3]==1).sum())

        _skeletons =[]
        _labels = []
        for ii in range(0, 4):
            print(skeletons[labels[:, ii]==1].shape)
            sk_idx = [np.random.choice(range(len(skeletons[labels[:, ii]==1])), size = min_len, replace = False)]
            print(sk_idx)
            _skeletons+=[skeletons[labels[:, ii]==1][sk_idx[0]]]
            _labels+=[labels[labels[:, ii]==1][sk_idx[0]]]
        skeletons = np.array(_skeletons).reshape(-1, 4)
        labels = np.array(_labels).reshape(-1, 4)
        self.skeletons = torch.tensor(skeletons).float()
        self.labels = torch.tensor(labels).float()

train_dataset = AlphaposeSkeletonData(train_json_dir, train_image_dir)


(229, 18, 3)
[array([  9, 178,  78, 139,  97,  28, 175,   8, 196,  96,  73, 174,  61,
       191,  95,  37, 173, 207, 218,  16, 220, 223,  39, 119, 117, 104,
        23, 145,  18,  98, 159, 217, 219,  40,  49, 193, 127,   7, 111,
       115,  69,  12, 208, 197, 144,  55, 199, 108,  21,  83, 143, 110,
       225, 215, 116, 195,  30,  52, 172,  81,  79, 177,  45, 164, 129,
         0,  51,  75,  14,  64, 114,  48,  38,  93,  84, 118, 221, 154,
       192,  87,  54, 121,  17, 112, 184,  10,  92, 224,  26,  70, 106,
        86, 124,  35,  80,  41,  47, 120,  32,  15,  34, 102, 180,  85,
        31, 201, 190,  33, 169, 135,  65, 176,  19, 123, 216, 149, 170,
       101,   6, 105,  89,  24, 188,  58,  77, 186, 211, 147, 137, 228,
         1, 227, 131, 132, 156, 198, 163, 128,  68, 204,  42, 206, 167,
        62,  25, 189,  46,  71,   5, 209,   4, 200, 165, 212,   2,  13,
       122, 202, 109, 185, 194, 160, 107])]
(163, 18, 3)
[array([ 75, 162,  19, 148,  13,  68,  51,  98,   3,  65, 127,  7

In [41]:
sum(train_dataset.labels[train_dataset.labels[:, 0]==1]), sum(train_dataset.labels[train_dataset.labels[:, 1]==1]),sum(train_dataset.labels[train_dataset.labels[:, 2]==1]),sum(train_dataset.labels[train_dataset.labels[:,3]==1])

(tensor([163.,   0.,   0.,   0.]),
 tensor([  0., 163.,   0.,   0.]),
 tensor([  0.,   0., 163.,   0.]),
 tensor([  0.,   0.,   0., 163.]))

In [39]:
train_dataset.labels.shape

torch.Size([4, 163, 4])