In [1]:
import os
dir = "C:\\Users\\user\\Desktop\\Pose"

target = ['front', 'back', 'left', 'right']

imgs = []
labels = []
for l in target:
    for img in os.listdir(os.path.join(dir, l)):
        imgs += [os.path.join(dir, l, img)]
        labels += [l]

In [2]:
from collections import Counter

Counter(labels)

Counter({'front': 35, 'back': 34, 'left': 35, 'right': 37})

In [3]:
imgs

['C:\\Users\\user\\Desktop\\Pose\\front\\0027_c4_f0023987.jpg',
 'C:\\Users\\user\\Desktop\\Pose\\front\\0030_c4_f0026288.jpg',
 'C:\\Users\\user\\Desktop\\Pose\\front\\0033_c2_f0061704.jpg',
 'C:\\Users\\user\\Desktop\\Pose\\front\\0042_c2_f0063664.jpg',
 'C:\\Users\\user\\Desktop\\Pose\\front\\0051_c4_f0030830.jpg',
 'C:\\Users\\user\\Desktop\\Pose\\front\\0078_c4_f0034045.jpg',
 'C:\\Users\\user\\Desktop\\Pose\\front\\0079_c2_f0066874.jpg',
 'C:\\Users\\user\\Desktop\\Pose\\front\\0114_c6_f0061083.jpg',
 'C:\\Users\\user\\Desktop\\Pose\\front\\0127_c2_f0075875.jpg',
 'C:\\Users\\user\\Desktop\\Pose\\front\\0135_c4_f0046746.jpg',
 'C:\\Users\\user\\Desktop\\Pose\\front\\0143_c4_f0049743.jpg',
 'C:\\Users\\user\\Desktop\\Pose\\front\\0147_c4_f0049659.jpg',
 'C:\\Users\\user\\Desktop\\Pose\\front\\0151_c4_f0051330.jpg',
 'C:\\Users\\user\\Desktop\\Pose\\front\\0162_c4_f0053991.jpg',
 'C:\\Users\\user\\Desktop\\Pose\\front\\0167_c2_f0084455.jpg',
 'C:\\Users\\user\\Desktop\\Pose\\front\

In [4]:
import PIL
import openpifpaf
import numpy as np
predictor = openpifpaf.Predictor(checkpoint='shufflenetv2k16')
pil_im = PIL.Image.open(imgs[0]).convert('RGB')
predictions, _, _ = predictor.pil_image(pil_im)
print(np.append(predictions[0].data, (predictions[0].data[5] + predictions[0].data[6])/2).reshape(-1, 3))

[[ 19.792934    14.7630825    0.7199818 ]
 [ 21.776253    12.397593     0.67566746]
 [ 17.446198    12.588003     0.6967247 ]
 [ 25.646606    12.870308     0.78534216]
 [ 14.204609    13.26079      0.74512255]
 [ 32.168194    24.775505     0.97032887]
 [  9.924631    25.385803     0.9769603 ]
 [ 38.786545    38.302593     0.8991085 ]
 [  2.4704173   38.093758     0.76294357]
 [ 32.113293    47.578293     0.77951366]
 [ 11.11957     45.89802      0.62511295]
 [ 29.258831    55.198666     0.9779419 ]
 [ 15.127205    55.6004       0.99817747]
 [ 27.748482    78.34921      0.9242825 ]
 [ 17.233473    78.37921      0.94345474]
 [ 27.00557    102.67316      0.88032126]
 [ 17.763308   101.88202      0.905094  ]
 [ 21.046413    25.080654     0.9736446 ]]


In [5]:
predictions[0].data.shape

(17, 3)

In [6]:
len([1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [7]:
A =\
[
    [1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1],
    [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1], #11
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1], #12
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0], #13
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0], #14
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0], #15
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0], #16
    [1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1]  #17
]

In [8]:
len([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

17

In [14]:
from datasets import TrainSkeletonData
import torch
from torch.utils.data import DataLoader
from model import GCN
import torch.nn as  nn
from torchvision import transforms

dir = "C:\\Users\\user\\Desktop\\pose-angle"



A =\
[
    [1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1],
    [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1], #11
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1], #12
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0], #13
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0], #14
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0], #15
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0], #16
    [1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1]  #17
]

A = torch.tensor(A).float()
in_feature = 3
num_class = 4
model = GCN(in_feature, num_class, A)
print(model)

learning_rate = 1e-3
batch_size= 30
epochs = 50
print(f"learning_rate : {learning_rate}")
print(f"batch_size : {batch_size}")
print(f"epochs : {epochs}")

loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

def train_loop(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    for batch, (X, y) in enumerate(dataloader):
        
        pred = model(X)
        loss=  loss_fn(pred,y)

        #Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if batch % 3 == 0:
            loss, current = loss.item(), batch * len(X)
            print(f'loss: {loss:>7f} [{current:>5d}/{size:>5d}]')

def test_loop(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    test_loss, correct = 0, 0

    with torch.no_grad():
        for X, y in dataloader:
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y.argmax(1)).type(torch.float).sum().item()

    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")

GCN(
  (feature_extractor): Sequential(
    (0): GCN_layer(
      (fc): Linear(in_features=3, out_features=4, bias=True)
    )
    (1): ReLU()
    (2): GCN_layer(
      (fc): Linear(in_features=4, out_features=8, bias=True)
    )
    (3): ReLU()
    (4): GCN_layer(
      (fc): Linear(in_features=8, out_features=16, bias=True)
    )
    (5): ReLU()
    (6): GCN_layer(
      (fc): Linear(in_features=16, out_features=16, bias=True)
    )
    (7): ReLU()
    (8): GCN_layer(
      (fc): Linear(in_features=16, out_features=16, bias=True)
    )
    (9): ReLU()
    (10): Flatten(start_dim=1, end_dim=-1)
    (11): Linear(in_features=288, out_features=4, bias=True)
  )
)
learning_rate : 0.001
batch_size : 30
epochs : 50


In [16]:
dataset = TrainSkeletonData(dir, True)

train_loader = DataLoader(dataset, batch_size = batch_size, shuffle= True)

loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

for t in range(epochs):
    print(f"Epoch {t+1}\n---------------------------------")
    train_loop(train_loader, model, loss_fn, optimizer)
    print("---------------------------------")
print("Done!")

make_skeleton
save file
skeletons.npy done
labels.npy done
Epoch 1
---------------------------------
loss: 0.191717 [    0/ 1260]
loss: 0.188456 [   90/ 1260]
loss: 0.431835 [  180/ 1260]
loss: 0.174800 [  270/ 1260]
loss: 0.113048 [  360/ 1260]
loss: 0.361208 [  450/ 1260]
loss: 0.174585 [  540/ 1260]
loss: 0.300218 [  630/ 1260]
loss: 0.141597 [  720/ 1260]
loss: 0.271741 [  810/ 1260]
loss: 0.233096 [  900/ 1260]
loss: 0.185821 [  990/ 1260]
loss: 0.303585 [ 1080/ 1260]
loss: 0.249685 [ 1170/ 1260]
---------------------------------
Epoch 2
---------------------------------
loss: 0.094657 [    0/ 1260]
loss: 0.476106 [   90/ 1260]
loss: 0.382426 [  180/ 1260]
loss: 0.282250 [  270/ 1260]
loss: 0.156332 [  360/ 1260]
loss: 0.217049 [  450/ 1260]
loss: 0.274550 [  540/ 1260]
loss: 0.113509 [  630/ 1260]
loss: 0.120655 [  720/ 1260]
loss: 0.288051 [  810/ 1260]
loss: 0.140359 [  900/ 1260]
loss: 0.183721 [  990/ 1260]
loss: 0.252876 [ 1080/ 1260]
loss: 0.223706 [ 1170/ 1260]
-----------

In [9]:
test_dir = "C:\\Users\\user\\Desktop\\Pose_test"
test_dir = SkeletonDataset(test_dir)
test_loader = DataLoader(test_dir)
print(len(test_loader.dataset))
def test_loop(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    test_loss, correct = 0, 0

    with torch.no_grad():
        for i, (X, y) in enumerate(dataloader):
            pred = model(X)

            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y.argmax(1)).type(torch.float).sum().item()
     
    print(correct)

    test_loss /= num_batches
    correct /= size
    
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")
test_loop(test_loader, model, loss_fn)



104
92.0
Test Error: 
 Accuracy: 88.5%, Avg loss: 0.892017 



In [10]:
model_name = "deep_GCN"
model_save_dir = "C:\\Users\\user\\Desktop\\GCN\\model_save"
torch.save(model.state_dict(), os.path.join(model_save_dir, f'{model_name}_weight.pth'))



In [4]:
from datasets import *
from PIL import Image

class RawData(Dataset):
    def __init__(self, dir):
        self.dir = dir
        self.images = os.listdir(dir)
        self.predictor = openpifpaf.Predictor(checkpoint='shufflenetv2k16')
    def __len__(self):
        return len(self.images)

    def __getitem__(self, index):
        image_dir = os.path.join(self.dir, self.images[index])
        
        image = Image.open(image_dir)
        
        predictions, _, _ = self.predictor.pil_image(image)

        if not predictions:
            return -1

        skt = np.append(predictions[0].data, (predictions[0].data[5] + predictions[0].data[6])/2).reshape(-1, 3)

        return torch.tensor(skt), image_dir

dir = "C:\\Users\\user\\Desktop\\RE-ID\\datasets\\DukeMTMC-reID\\bounding_box_train"

datasets = RawData(dir = dir)

In [5]:
import shutil
import numpy as np

target = np.array(['front', 'back', 'left', 'right'])
save_dir = "C:\\Users\\user\\Desktop\\temp"


for t in target:
    if not os.path.exists(os.path.join(save_dir, t)):
        os.mkdir(os.path.join(save_dir, t))

for data in datasets:
    if data == -1:
        continue

    pred = model1(data[0].unsqueeze(0))
    image_path = data[1]
    image_name = image_path.split('\\')[-1]
    
    
    shutil.copyfile(image_path, os.path.join(save_dir, target[pred.argmax()], image_name))


In [39]:
X_t.unsqueeze(0)

tensor([[[ 19.7854,  14.7728,   0.7215],
         [ 21.7721,  12.4053,   0.6782],
         [ 17.4371,  12.5962,   0.7018],
         [ 25.6621,  12.8388,   0.7861],
         [ 14.2054,  13.2253,   0.7428],
         [ 32.1866,  24.7745,   0.9703],
         [  9.9523,  25.3505,   0.9770],
         [ 38.7743,  38.3007,   0.8980],
         [  2.5161,  38.0710,   0.7616],
         [ 32.0798,  47.6180,   0.7788],
         [ 11.1834,  45.8651,   0.6192],
         [ 29.2627,  55.1673,   0.9779],
         [ 15.1179,  55.5573,   0.9982],
         [ 28.0386,  78.5428,   0.9248],
         [ 17.2342,  78.3669,   0.9438],
         [ 27.8211, 102.7684,   0.8719],
         [ 17.7365, 101.9234,   0.9054],
         [ 21.0694,  25.0625,   0.9736]]])

In [32]:
X_t = train_loader.dataset.__getitem__(0)[0]
X_t = torch.tensor(X_t)
print(X_t)

tensor([[ 19.7854,  14.7728,   0.7215],
        [ 21.7721,  12.4053,   0.6782],
        [ 17.4371,  12.5962,   0.7018],
        [ 25.6621,  12.8388,   0.7861],
        [ 14.2054,  13.2253,   0.7428],
        [ 32.1866,  24.7745,   0.9703],
        [  9.9523,  25.3505,   0.9770],
        [ 38.7743,  38.3007,   0.8980],
        [  2.5161,  38.0710,   0.7616],
        [ 32.0798,  47.6180,   0.7788],
        [ 11.1834,  45.8651,   0.6192],
        [ 29.2627,  55.1673,   0.9779],
        [ 15.1179,  55.5573,   0.9982],
        [ 28.0386,  78.5428,   0.9248],
        [ 17.2342,  78.3669,   0.9438],
        [ 27.8211, 102.7684,   0.8719],
        [ 17.7365, 101.9234,   0.9054],
        [ 21.0694,  25.0625,   0.9736]])


In [13]:
torch.concat((X_t.reshape(1, X_t.shape[0], X_t.shape[1]), X_t.reshape(1, X_t.shape[0], X_t.shape[1])), axis = 0)

tensor([[[ 19.7854,  14.7728,   0.7215],
         [ 21.7721,  12.4053,   0.6782],
         [ 17.4371,  12.5962,   0.7018],
         [ 25.6621,  12.8388,   0.7861],
         [ 14.2054,  13.2253,   0.7428],
         [ 32.1866,  24.7745,   0.9703],
         [  9.9523,  25.3505,   0.9770],
         [ 38.7743,  38.3007,   0.8980],
         [  2.5161,  38.0710,   0.7616],
         [ 32.0798,  47.6180,   0.7788],
         [ 11.1834,  45.8651,   0.6192],
         [ 29.2627,  55.1673,   0.9779],
         [ 15.1179,  55.5573,   0.9982],
         [ 28.0386,  78.5428,   0.9248],
         [ 17.2342,  78.3669,   0.9438],
         [ 27.8211, 102.7684,   0.8719],
         [ 17.7365, 101.9234,   0.9054],
         [ 21.0694,  25.0625,   0.9736]],

        [[ 19.7854,  14.7728,   0.7215],
         [ 21.7721,  12.4053,   0.6782],
         [ 17.4371,  12.5962,   0.7018],
         [ 25.6621,  12.8388,   0.7861],
         [ 14.2054,  13.2253,   0.7428],
         [ 32.1866,  24.7745,   0.9703],
         [  9.

In [14]:
torch.matmul(A.float(),torch.concat((X_t.reshape(1, X_t.shape[0], X_t.shape[1]), X_t.reshape(1, X_t.shape[0], X_t.shape[1])), axis = 0))

tensor([[[166.5835, 225.6863,   6.9985],
         [ 67.2195,  40.0170,   2.1859],
         [ 51.4279,  40.5943,   2.1661],
         [ 47.4341,  25.2441,   1.4643],
         [ 31.6425,  25.8214,   1.4446],
         [ 92.0303,  88.1377,   2.8419],
         [ 33.5378,  88.4840,   2.7122],
         [103.0406, 110.6932,   2.6471],
         [ 23.6518, 109.2865,   2.3578],
         [ 70.8540,  85.9187,   1.6768],
         [ 13.6995,  83.9361,   1.3808],
         [ 78.3707, 158.7726,   2.8763],
         [ 53.4215, 158.9867,   2.9156],
         [ 85.1223, 236.4785,   2.7746],
         [ 50.0886, 235.8476,   2.8474],
         [ 55.8596, 181.3112,   1.7967],
         [ 34.9706, 180.2903,   1.8492],
         [127.3744, 200.6849,   5.6184]],

        [[166.5835, 225.6863,   6.9985],
         [ 67.2195,  40.0170,   2.1859],
         [ 51.4279,  40.5943,   2.1661],
         [ 47.4341,  25.2441,   1.4643],
         [ 31.6425,  25.8214,   1.4446],
         [ 92.0303,  88.1377,   2.8419],
         [ 33.

In [ ]:
train_loader

In [ ]:
torch.matmul(A.float(), X_t)

tensor([[166.5835, 225.6864,   6.9985],
        [ 67.2195,  40.0170,   2.1859],
        [ 51.4279,  40.5943,   2.1661],
        [ 47.4341,  25.2441,   1.4643],
        [ 31.6425,  25.8214,   1.4446],
        [ 92.0303,  88.1377,   2.8419],
        [ 33.5378,  88.4840,   2.7122],
        [103.0406, 110.6932,   2.6471],
        [ 23.6518, 109.2865,   2.3578],
        [ 70.8540,  85.9187,   1.6768],
        [ 13.6995,  83.9361,   1.3808],
        [ 78.3707, 158.7726,   2.8763],
        [ 53.4215, 158.9867,   2.9156],
        [ 85.1223, 236.4785,   2.7746],
        [ 50.0886, 235.8476,   2.8474],
        [ 55.8596, 181.3112,   1.7967],
        [ 34.9706, 180.2903,   1.8492],
        [127.3744, 200.6849,   5.6184]])

In [ ]:
print(A.type_as('float32'))

TypeError: type_as(): argument 'other' (position 1) must be Tensor, not str

In [ ]:
A.float()

tensor([[1., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1.],
        [1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1.],
        [0., 0.,

In [18]:
X_t = train_loader.dataset.__getitem__(0)

In [19]:
torch.tensor(X_t[0])

tensor([[ 19.7854,  14.7728,   0.7215],
        [ 21.7721,  12.4053,   0.6782],
        [ 17.4371,  12.5962,   0.7018],
        [ 25.6621,  12.8388,   0.7861],
        [ 14.2054,  13.2253,   0.7428],
        [ 32.1866,  24.7745,   0.9703],
        [  9.9523,  25.3505,   0.9770],
        [ 38.7743,  38.3007,   0.8980],
        [  2.5161,  38.0710,   0.7616],
        [ 32.0798,  47.6180,   0.7788],
        [ 11.1834,  45.8651,   0.6192],
        [ 29.2627,  55.1673,   0.9779],
        [ 15.1179,  55.5573,   0.9982],
        [ 28.0386,  78.5428,   0.9248],
        [ 17.2342,  78.3669,   0.9438],
        [ 27.8211, 102.7684,   0.8719],
        [ 17.7365, 101.9234,   0.9054],
        [ 21.0694,  25.0625,   0.9736]])

In [24]:
X_t

(array([[ 19.785437  ,  14.772844  ,   0.7215067 ],
        [ 21.772055  ,  12.4052925 ,   0.67824465],
        [ 17.437067  ,  12.596153  ,   0.70178014],
        [ 25.66205   ,  12.838848  ,   0.7861026 ],
        [ 14.205389  ,  13.225267  ,   0.74279624],
        [ 32.186584  ,  24.774513  ,   0.97027415],
        [  9.952294  ,  25.350466  ,   0.97698075],
        [ 38.774258  ,  38.300705  ,   0.8980057 ],
        [  2.5161135 ,  38.071003  ,   0.7615855 ],
        [ 32.079758  ,  47.617958  ,   0.7787828 ],
        [ 11.183401  ,  45.865063  ,   0.6192074 ],
        [ 29.262691  ,  55.167286  ,   0.97787946],
        [ 15.1179085 ,  55.557304  ,   0.9981807 ],
        [ 28.03856   ,  78.54279   ,   0.9248307 ],
        [ 17.234167  ,  78.36692   ,   0.94381   ],
        [ 27.821056  , 102.76838   ,   0.87185735],
        [ 17.736483  , 101.92338   ,   0.9053639 ],
        [ 21.069439  ,  25.062489  ,   0.97362745]], dtype=float32),
 tensor([1., 0., 0., 0.]))

In [27]:
test_loader.dataset.


In [31]:
for i in range(24):
    X_t = test_loader.dataset.__getitem__(i)
    print(model(torch.tensor(X_t[0]).reshape(-1, X_t[0].shape[0], X_t[0].shape[1])).argmax(), X_t[1].argmax(), model(torch.tensor(X_t[0]).reshape(-1, X_t[0].shape[0], X_t[0].shape[1])).argmax()== X_t[1].argmax())

tensor(1) tensor(0) tensor(False)
tensor(0) tensor(0) tensor(True)
tensor(0) tensor(0) tensor(True)
tensor(0) tensor(0) tensor(True)
tensor(0) tensor(0) tensor(True)
tensor(0) tensor(0) tensor(True)
tensor(3) tensor(1) tensor(False)
tensor(0) tensor(1) tensor(False)
tensor(3) tensor(1) tensor(False)
tensor(3) tensor(1) tensor(False)
tensor(0) tensor(1) tensor(False)
tensor(2) tensor(1) tensor(False)
tensor(1) tensor(2) tensor(False)
tensor(1) tensor(2) tensor(False)
tensor(1) tensor(2) tensor(False)
tensor(2) tensor(2) tensor(True)
tensor(2) tensor(2) tensor(True)
tensor(2) tensor(2) tensor(True)
tensor(1) tensor(3) tensor(False)
tensor(3) tensor(3) tensor(True)
tensor(3) tensor(3) tensor(True)
tensor(3) tensor(3) tensor(True)
tensor(3) tensor(3) tensor(True)
tensor(3) tensor(3) tensor(True)


In [17]:
X_t[0]

tensor([19.7854, 14.7728,  0.7215])

In [16]:
model(torch.tensor(X_t[0]))

C:\Users\user\anaconda3\envs\RE-ID_3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.


RuntimeError: size mismatch, got 18, 18x18,3

In [ ]:
a = np.array(['front', 'back', 'left', 'right']) == X_t[1]

In [44]:
model_save_dir = "./model_save"

torch.save(model.state_dict(), os.path.join(model_save_dir, 'model_weights.pth'))


In [1]:
from datasets import *
import torch
from torch.utils.data import DataLoader
from model import GCN
import torch.nn as  nn
from torchvision import transforms


dir = "C:\\Users\\user\\Desktop\\pose-angle"
model_save_dir = "./model_save"
model_name = "model_05_12_13_43"

dataset = TrainSkeletonData(dir, make_skeleton=False)

train_loader = DataLoader(dataset, batch_size = 32, shuffle= True)


A =\
[
    [1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1],
    [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1], #11
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1], #12
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0], #13
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0], #14
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0], #15
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0], #16
    [1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1]  #17
]

A = torch.tensor(A).float()
in_feature = 3
num_class = 4
model1 = GCN(in_feature, num_class, A)
print(model1)

learning_rate = 1e-3
batch_size= 32
epochs = 100
print(f"learning_rate : {learning_rate}")
print(f"batch_size : {batch_size}")
print(f"epochs : {epochs}")

loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model1.parameters(), lr=learning_rate)    

for t in range(epochs):
    print(f"Epoch {t+1}\n---------------------------------")
    size = len(train_loader.dataset)
    for batch, (X, y) in enumerate(train_loader):
        pred = model1(X)
        loss=  loss_fn(pred,y)

        #Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if batch % 32 == 0:
            loss, current = loss.item(), batch * len(X)
            print(f'loss: {loss:>7f} [{current:>5d}/{size:>5d}]')

    print("---------------------------------")
print("Done!")

torch.save(model1.state_dict(), os.path.join(model_save_dir, f'{model_name}_weight.pth'))

GCN(
  (feature_extractor): Sequential(
    (0): GCN_layer(
      (fc): Linear(in_features=3, out_features=4, bias=True)
    )
    (1): ReLU()
    (2): GCN_layer(
      (fc): Linear(in_features=4, out_features=8, bias=True)
    )
    (3): ReLU()
    (4): GCN_layer(
      (fc): Linear(in_features=8, out_features=16, bias=True)
    )
    (5): ReLU()
    (6): GCN_layer(
      (fc): Linear(in_features=16, out_features=16, bias=True)
    )
    (7): ReLU()
    (8): GCN_layer(
      (fc): Linear(in_features=16, out_features=16, bias=True)
    )
    (9): ReLU()
    (10): GCN_layer(
      (fc): Linear(in_features=16, out_features=32, bias=True)
    )
    (11): ReLU()
    (12): GCN_layer(
      (fc): Linear(in_features=32, out_features=32, bias=True)
    )
    (13): ReLU()
    (14): Flatten(start_dim=1, end_dim=-1)
    (15): Linear(in_features=576, out_features=4, bias=True)
  )
)
learning_rate : 0.001
batch_size : 32
epochs : 100
Epoch 1
---------------------------------
loss: 1095.698360 [    

In [3]:
from datasets import *
import torch
from torch.utils.data import DataLoader
from model import GCN
import torch.nn as  nn
from torchvision import transforms

test_dir = "C:\\Users\\user\\Desktop\\Pose_test"
test_datasets = TestDataset(test_dir)

print("전체 Test 데이터 개수 : ", len(test_datasets))
def test_loop(dataset, model, loss_fn):
    size = len(dataset)
    test_loss, correct, wrong = 0, 0, 0
    model.eval()
    print("------------------------------")
    with torch.no_grad():
        for i, data in enumerate(dataset):
            if data == -1:
                print('log : skeleton_error')
                wrong += 1
                continue
            X,y = torch.tensor(data[0]).unsqueeze(0), data[1].unsqueeze(0)
            
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y.argmax(1)).type(torch.float).sum().item()
    print("------------------------------")
    print("맞은 개수 : ", correct)

    test_loss /= (size -wrong)
    correct /= (size -wrong)
    
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")


test_loop(test_datasets, model1, loss_fn)

전체 Test 데이터 개수 :  99
------------------------------
log : skeleton_error
------------------------------
맞은 개수 :  87.0
Test Error: 
 Accuracy: 88.8%, Avg loss: 0.335525 



In [17]:
test_loop(test_datasets, model, loss_fn)

AttributeError: 'TestDataset' object has no attribute 'dataset'